import "./globals.css";
import { Inter } from "next/font/google";
import getCurrentUser from "./actions/getCurrentUser";
import Navbar from "./components/nav/Navbar";
import { User } from "@prisma/client";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getCurrentUser();

  return (
    <html lang="ja">
      <body className={inter.className}>
        <Navbar user={user as User} />
        {children}
      </body>
    </html>
  );
}
