import "./globals.css";
import { Inter } from "next/font/google";
import getCurrentUser from "./actions/getCurrentUser";
import Header from "./components/layout/Header";
import { User } from "@prisma/client";
import BottomNav from "./components/layout/BottomNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getCurrentUser();

  return (
    <html lang="ja">
      <body
        className={`${inter.className} bg-gradient-to-r from-indigo-200 via-purple-200 to-pink-200 flex items-center flex-col h-full min-h-screen w-screen pb-[62px] max-h-[100vh]`}
      >
        <div className="relative max-w-[450px] w-[97%] max-h-full m-2 p-4 bg-white rounded-3xl max-h-screen">
          <Header
            user={
              user as unknown as Omit<
                User,
                "createdAt" | "updatedAt" | "emailVerified"
              >
            }
          />
          <main className="overflow-y-auto min-h-[80vh] max-h-[80vh]">{children}</main>
          <BottomNav />
        </div>
      </body>
    </html>
  );
}
